<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.assert" Version="3.2.2" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
    <ProjectReference Include="..\AssertEventually\AssertEventually.csproj" />
  </ItemGroup>

</Project>
